pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Get some code from github repository
                git "https://github.com/kennethihezie/learn-jenkins.git"
            }
        }
    }
}